# Generated by Django 4.0.2 on 2022-02-18 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Granary',
            fields=[
                ('granary_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('Stock_sugar_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_rice_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_wheat_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_kerosine_in_l', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('color', models.CharField(default='----------', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('monthly_income_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Quota_sugar_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Quota_rice_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Quota_wheat_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Quota_kerosine_in_l', models.PositiveBigIntegerField(default=0)),
                ('Price_sugar_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Price_rice_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Price_wheat_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Price_kerosine_in_l', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RationStore',
            fields=[
                ('store_id', models.CharField(default='0000000000', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('owner_name', models.CharField(default='----------', max_length=20)),
                ('taluk_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(78), django.core.validators.MinValueValidator(1)])),
                ('ward_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1)])),
                ('no_of_dependents', models.PositiveIntegerField(default=0)),
                ('no_of_yellow_cards', models.PositiveIntegerField(default=0)),
                ('no_of_pink_cards', models.PositiveIntegerField(default=0)),
                ('no_of_blue_cards', models.PositiveIntegerField(default=0)),
                ('no_of_white_cards', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_sugar_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_rice_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_wheat_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_kerosine_in_l', models.PositiveBigIntegerField(default=0)),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.granary')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rationstore')),
            ],
        ),
        migrations.AddField(
            model_name='rationstore',
            name='sa',
            field=models.ManyToManyField(through='management.StockAcquisition', to='management.Granary'),
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('card_no', models.CharField(default='0000000000', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('taluk_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(78), django.core.validators.MinValueValidator(1)])),
                ('no_of_adults', models.PositiveIntegerField(default=1)),
                ('no_of_children', models.PositiveIntegerField(default=0)),
                ('ward_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1)])),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.quota')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rationstore')),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_purchase', models.DateField(null=True)),
                ('rice_purchased_in_kg', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sugar_purchased_in_kg', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('wheat_purchased_in_kg', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('kerosine_purchased_in_l', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rationcard')),
            ],
        ),
        migrations.AddField(
            model_name='granary',
            name='sa',
            field=models.ManyToManyField(through='management.StockAcquisition', to='management.RationStore'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card_no', models.CharField(default='000000000000', max_length=12, unique=True)),
                ('name_of_dependent', models.CharField(default='----------', max_length=20)),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rationcard')),
            ],
        ),
    ]
