# Generated by Django 4.0.2 on 2022-02-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_sugar_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_rice_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_wheat_in_kg', models.PositiveBigIntegerField(default=0)),
                ('Stock_kerosine_in_l', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rationstore',
            name='Stock_kerosine_in_l',
        ),
        migrations.RemoveField(
            model_name='rationstore',
            name='Stock_rice_in_kg',
        ),
        migrations.RemoveField(
            model_name='rationstore',
            name='Stock_sugar_in_kg',
        ),
        migrations.RemoveField(
            model_name='rationstore',
            name='Stock_wheat_in_kg',
        ),
        migrations.AddField(
            model_name='granary',
            name='sa',
            field=models.ManyToManyField(through='management.StockAcquisition', to='management.RationStore'),
        ),
        migrations.AddField(
            model_name='rationstore',
            name='sa',
            field=models.ManyToManyField(through='management.StockAcquisition', to='management.Granary'),
        ),
        migrations.AlterField(
            model_name='rationstore',
            name='no_of_blue_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rationstore',
            name='no_of_dependents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rationstore',
            name='no_of_pink_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rationstore',
            name='no_of_white_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rationstore',
            name='no_of_yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockacquisition',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.granary'),
        ),
        migrations.AddField(
            model_name='stockacquisition',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rationstore'),
        ),
    ]
