# Generated by Django 4.0.2 on 2022-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='monthly_income_cap',
        ),
        migrations.AddField(
            model_name='quota',
            name='category',
            field=models.CharField(default='----------', max_length=10),
        ),
        migrations.AddField(
            model_name='quota',
            name='criteria',
            field=models.CharField(default='---------', max_length=100),
        ),
    ]
