# Generated by Django 4.0.2 on 2022-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_quota_monthly_income_cap_quota_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='criteria',
            field=models.CharField(default='---------', max_length=200),
        ),
    ]
