# Generated by Django 4.0.2 on 2022-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_stockacquisition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granary',
            name='item_id',
        ),
        migrations.AddField(
            model_name='granary',
            name='Stock_kerosine_in_l',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='granary',
            name='Stock_rice_in_kg',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='granary',
            name='Stock_sugar_in_kg',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='granary',
            name='Stock_wheat_in_kg',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
