# Generated by Django 4.0.2 on 2022-02-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_quota_criteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='Price_kerosine_in_l',
            new_name='Price_kerosine_per_l',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Price_rice_in_kg',
            new_name='Price_rice_per_kg',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Price_sugar_in_kg',
            new_name='Price_sugar_per_kg',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Price_wheat_in_kg',
            new_name='Price_wheat_per_kg',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Quota_kerosine_in_l',
            new_name='Quota_kerosine_in_l_per_member',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Quota_rice_in_kg',
            new_name='Quota_rice_in_kg_per_member',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Quota_sugar_in_kg',
            new_name='Quota_sugar_in_kg_per_member',
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='Quota_wheat_in_kg',
            new_name='Quota_wheat_in_kg_per_member',
        ),
    ]
