# Generated by Django 4.0.2 on 2022-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_granary_item_id_granary_stock_kerosine_in_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granary',
            name='granary_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
