# Generated by Django 4.0.2 on 2022-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rationcard_nod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='nod',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
