# Generated by Django 4.0.2 on 2022-02-19 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_rationcard_nod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rationcard',
            old_name='nod',
            new_name='no_of_dependants',
        ),
        migrations.RenameField(
            model_name='rationcard',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='taluk_no',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MaxValueValidator(78), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='ward_no',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
