# Generated by Django 4.0.2 on 2022-02-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_rationcard_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationcard',
            name='no_of_adults',
        ),
        migrations.RemoveField(
            model_name='rationcard',
            name='no_of_children',
        ),
    ]
