# Generated by Django 4.0.2 on 2022-02-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_rationcard_no_of_adults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='id',
        ),
        migrations.AlterField(
            model_name='dependent',
            name='aadhar_card_no',
            field=models.CharField(default='000000000000', max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
