# Generated by Django 4.0.2 on 2022-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_dependent_id_alter_dependent_aadhar_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='no_of_dependants',
            field=models.IntegerField(editable=False),
        ),
    ]
