# Generated by Django 4.0.2 on 2022-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_rationcard_no_of_dependants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationstore',
            name='store_id',
            field=models.CharField(default='0000000000', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
