# Generated by Django 4.0.2 on 2022-02-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_rationstore_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granary',
            name='granary_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
