# Generated by Django 4.0.2 on 2022-02-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_granary_granary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependent',
            old_name='card_no',
            new_name='card',
        ),
    ]
